name: file_syncer_cli
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: ^3.9.3

# Add regular dependencies here.
dependencies:
  watcher: ^1.1.2
  http: ^1.5.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
